@startuml
left to right direction
skinparam classAttributeIconSize 0
skinparam shadowing false

class Usuario {
  - idUsuario
  - nombre
  - email
  - tipoUsuario
}

class Campo {
  - idCampo
  - nombre
  - ubicacion
}

class Hoyo {
  - idHoyo
  - numero
  - par
  - distancia
}

class Sesion {
  - idSesion
  - fechaHoraInicio
  - fechaHoraFin
  - estado
}

class EventoDetectado {
  - idEventoDetectado
  - fechaHora
  - valido
}

class Clip {
  - idClip
  - fechaHoraCreacion
  - duracion
  - urlAlmacenamiento
  - favorito
  - fechaExpiracion
}

Campo "1" o-- "1..*" Hoyo : contiene
Usuario "1" -- "0..*" Sesion : realiza
Hoyo "1" -- "0..*" Sesion : alberga
Sesion "1" *-- "1..*" EventoDetectado : incluye
EventoDetectado "1" -- "0..1" Clip : genera

@enduml